### ISSUE TITLE
Action fails even when build succeeds

### ISSUE THREAD

**Issue by pkrawc** [amondnet/vercel-action#11]
```bash
Error! Failed to find deployment "https://<url>.now.sh in <team>
##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

The deployment it was trying to find does actually exist and is here: https://avail-design-site-jsh7mexrg.now.sh/

**Comment by amondnet** [comment]
@pkrawc 
https://github.com/amondnet/vercel-action#inputs
> scope : If you are working in a team scope, you should set this value to your team ID.

**Comment by pkrawc** [comment]
If I add the scope then the action succeeds doesn't create a new deployment, it links to the last successful deployment.

**Comment by amondnet** [comment]
https://vercel.com/docs/api#endpoints/deployments/create-a-new-deployment/force-a-new-deployment
Deploying again with the same request would yield the same response, with the same ID and URL due to no differences to the files or configuration.

**Comment by pkrawc** [comment]
Interesting, I wasn't aware that vercel was doing a checksum on old and new files.

I'll definitely explore this (I potentially didn't have changes to the site as I was trying to push a new deploy) and close this if that's the case.

Thanks for your responses!

**Comment by klaasman** [comment]
I ran into the same issue and can confirm that setting the `scope` fixed it :+1:

**Comment by pkrawc** [comment]
_To close the loop here_

My problem was twofold.

1. I did not have the `scope` field set initially.
2. When I did have the `scope` field set there was no change in the files to deploy. I didn't know there was a check on this so it makes sense not to run a true build for the same files over and over.

Once the `scope` field was set and there was a change in the build, this action worked perfectly.
