### ISSUE TITLE
Custom env in action

### ISSUE THREAD

**Issue by jonyw4** [amondnet/vercel-action#13]
Its possible to send a custom env for Vercel use in build time? I think that it's a huge feature for people that need to deploy an app in Vercel using a env that its created in Github action.

**Comment by klaasman** [comment]
Vercel CLI supports setting build envs using the `--build-env` flag, so I think you should be able to set these variables with the `vercel-args` input:
```
vercel-args: '--build-env CUSTOM_VAR=value'

**Comment by jonyw4** [comment]
Ok, nice! Thanks!
