### ISSUE TITLE
Don't send new comment for every pushed commit and just edit existed one

### ISSUE THREAD

**Issue by AlexRekish** [amondnet/vercel-action#15]
Is it possible to edit an existing deploy comment instead of sending a new one?

**Comment by aulneau** [comment]
Yes, was just thinking about this. The proper Vercel action does this, too.

**Comment by aulneau** [comment]
@amondnet I believe the issue is that you're using `octokit.repos.listCommentsForCommit` instead of `octokit.issues.listComments`:

```tsx
await octokit.issues.listComments({
  ...context.repo,
  issue_number: context.issue.number,
});
```

I don't think you'd update the comment if it's for a commit -- meaning push, such as a prod deployment when pushed to `master` -- right?

**Comment by amondnet** [comment]
@aulneau Yes, you are right.
