### ISSUE TITLE
Upgrade vercel cli version to 27.0.1 

### ISSUE THREAD

**Issue by SamiHmz** [amondnet/vercel-action#170]
We 've got an issue says that the vercel cli version is not found 
i think upgrading the vercel version in the package.json to v  `27.0.1` would solve the problem

![image](https://user-images.githubusercontent.com/45699898/178501529-865efa91-2f80-4b42-9f0b-ec7727cab5e6.png)

**Comment by vitorbal** [comment]
It sounds like this is solved on the latest patch version of vercel cli (27.0.2): https://github.com/vercel/vercel/issues/8125

**Comment by mainawycliffe** [comment]
Yeah, I saw that and vercel cli works fine locally on the latest version, but for some reason, this doesn't work on the Github Actions and if you look at the version being run is version is 27.0.2 beta, which I checked and it doesn't exist.
![image](https://user-images.githubusercontent.com/12270550/178524020-969da515-8928-4291-94ad-2c1e62b01e38.png)

**Comment by anasmebarki1996-c4t** [comment]
> It sounds like this is solved on the latest patch version of vercel cli (27.0.2): [vercel/vercel#8125](https://github.com/vercel/vercel/issues/8125)

Github actions still uses **Vercel CLI 27.0.1  (beta)**

**Comment by vitorbal** [comment]
It looks like there's some sort of github actions cache for npx packages at play, because this prints 27.0.2:
<img width="700" alt="Screen Shot 2022-07-12 at 13 06 34" src="https://user-images.githubusercontent.com/626038/178540524-94c47984-828c-482d-8108-5ef47325bda8.png">

But the `amondnet/vercel-action` action runs `npx vercel` (no `@latest`), and that always resolves to 27.0.1. 🤔

**Comment by mainawycliffe** [comment]
@vitorbal ah, this makes sense. This would solve the problem for this specific issue, what would be great is respecting the version in `package.json` and we can control what version of the vercel cli is used.

**Comment by vitorbal** [comment]
@mainawycliffe agreed, I am attempting to get that working here: https://github.com/amondnet/vercel-action/pull/171
But the checks are failing. Take a look (if you're interested) if you can spot the problem!

**Comment by mainawycliffe** [comment]
@vitorbal let me take a look when I get a chance

**Comment by felipe-chamas** [comment]
What can we do in repos using this action meanwhile?

**Comment by mgtitimoli** [comment]
I have just left a [comment](https://github.com/amondnet/vercel-action/issues/168#issuecomment-1182480807) on another issue explaining the details behind this issue and how to solve it. I hope it helps.

**Comment by aleCeres** [comment]
I'm facing the same issue here

**Comment by TheSNSCompany** [comment]
ditto, broke my github actions.  How do we specify to keep it on version 25?  I tried `amondnet/vercel-action@v25` but it still used 27.

**Comment by evelynstender** [comment]
I'm having the same issue here
