### ISSUE TITLE
please support prebuilt

### ISSUE THREAD

**Issue by kota-nakagawa** [amondnet/vercel-action#174]
Hi !

I would like to use a pre-built, 

Is it possible to add option here?

https://vercel.com/blog/build-output-api#powering-new-capabilities-with-vercel-cli

<img width="1187" alt="スクリーンショット 2022-07-25 18 20 36" src="https://user-images.githubusercontent.com/36807675/180745777-6714a39b-d0b5-4680-bedb-d45246c20dce.png">

**Comment by amondnet** [comment]
@kota-nakagawa 
https://github.com/amondnet/vercel-action/blob/9001bb7086d6c5414c4f8e500a89e8fa632eaefe/.github/workflows/example-nextjs.yml#L37
