### ISSUE TITLE
`v25` tag has not been updated

### ISSUE THREAD

**Issue by EndBug** [amondnet/vercel-action#178]
The current `v25` tag points to `v25.0.0` instead of `v25.1.0`. A solution would be to add an action that updates the major version tag automatically.

**Comment by vickkhera** [comment]
It currently points to v25.1.0 even thought 25.2.0 is out.

**Comment by EndBug** [comment]
Seems not to be the case anymore: 
![image](https://github.com/user-attachments/assets/b0f92d6b-57af-4364-b946-eb6dff60ee3b)
