### ISSUE TITLE
Support deploy --archive argument

### ISSUE THREAD

**Issue by frank7huysen** [amondnet/vercel-action#188]
Hello,

According to [vercelignore not ignoring files in build output](https://github.com/vercel/vercel/issues/8571) we have to pass `--archive` as one of the deploy command options. Unfortunately, this is not possible using Vercel args.

Pipeline example
```
vercel-args: "--prebuilt --archive=tgz"

Vercel CLI 25.1.0
Error! unknown or unexpected option: --archive
```
Therefore, it would be nice if we could pass --archive as one of the vercel-args.

Thanks!

**Comment by frank7huysen** [comment]
I guess the const VERCEL_BIN = 'vercel@25.1.0'; needs at least version 28.0.0 if possible. See release https://github.com/vercel/vercel/releases/tag/vercel%4028.0.0

**Comment by frank7huysen** [comment]
Oops related Pull Request [https://github.com/amondnet/vercel-action/pull/183](https://github.com/amondnet/vercel-action/pull/183)

**Comment by rcerljenko** [comment]
@amondnet could you tag a new version with the latest changes such as `vercel-version` param?

**Comment by amondnet** [comment]
@rcerljenko https://github.com/amondnet/vercel-action/releases/tag/v25.1.1

**Comment by rcerljenko** [comment]
thanks!
