### ISSUE TITLE
Any way to use `vercel.json`?

### ISSUE THREAD

**Issue by brycewray** [amondnet/vercel-action#225]
As the title says — is there a way to get this excellent GHA to “see” and respect a project’s top-level vercel.json file, such as to provide Cache-Control headers and so forth?

**Comment by amondnet** [comment]
@brycewray 
Just place vercel.json in your distribution directory.

https://github.com/amondnet/vercel-action/blob/master/example/angular/src/vercel.json
https://github.com/amondnet/vercel-action/tree/master/example/nextjs
https://github.com/amondnet/vercel-action/blob/master/example/static/vercel.json
https://github.com/amondnet/vercel-action/blob/master/example/express-basic-auth/vercel.json

**Comment by brycewray** [comment]
@amondnet Had already tried without success. It’s a Hugo project that creates the distribution dir (`public`) on the fly. I suppose I could put it in the `static` dir and let Hugo copy it there. However, I’ve already found another way, by using a variation on the [officially suggested method](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel).

Thanks for the reply!
