### ISSUE TITLE
Monorepo support for sending build directly to vercel

### ISSUE THREAD

**Issue by jakeleventhal** [amondnet/vercel-action#231]
The way to publish a pre-built vercel application is shown in the README like this
```
{
  "builds": [
    { "src": "{{Source for distribution}}", "use": "@vercel/static" }
  ]
}
```

There isnt an example for how to deploy a pre-built application if there are multiple applications in the same repo. Currently I am just skipping the build in GH actions and redoing the pnpm install + next build in vercel

**Comment by fgmamoru** [comment]
you can move the working-directory to the subfolder.

**Comment by zhenwenc** [comment]
what the `{{ Source for distribution }}` value suppose to be for NextJS project? `.next/**`?
