### ISSUE TITLE
Deployment succeeds but action log says it failed

### ISSUE THREAD

**Issue by forde** [amondnet/vercel-action#27]
HI.

The setup in my **.yml** file is:

    name: Deployment

    on:
      push:
        branches:
      - master

    jobs:
     deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: 'Set build id'
        id: build_id
        run: echo "::set-output name=id::$(date +%s)"

      - name: Deploy master branch
        if: github.ref == 'refs/heads/master'
        uses: amondnet/vercel-action@v19.0.1+2
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          vercel-args: '--prod -b BUILD=${{ steps.build_id.outputs.id }} -b BUILD_BRANCH=master -b ENVIRONMENT=production'
          vercel-org-id: ${{ secrets.ZEIT_ORG_ID }}
          vercel-project-id: ${{ secrets.ZEIT_PRODUCTION_PROJECT_ID }}

On push to master the action gets triggered but when it finishes action log says it failed (even tho code gets deployed and logs on vercel.com confirm succesful deployment)

Action logs:

    https://*****************.vercel.app- Queued

    - Queued

    - Building

    - Building

    Production: https://***************** [3m]
    Due to "builds" existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings

    set preview-url output
    /usr/local/bin/npx vercel inspect https://*****************.vercel.app -t ***
    Vercel CLI 19.2.0

    Vercel CLI 19.2.0
    - Fetching deployment "https://*****************.vercel.app" in *****

    - Fetching deployment "https://*****************.vercel.app" in *****

    Error! Failed to find deployment "https://*****************.vercel.app" in *****

    Error! Failed to find deployment "https://*****************.vercel.app" in *****
    ##[error]The process '/usr/local/bin/npx' failed with exit code 1

Any ideas?

**Comment by AlexRekish** [comment]
same issue with such logs:
<img width="826" alt="Снимок экрана 2020-08-07 в 14 38 24" src="https://user-images.githubusercontent.com/37471019/89642056-b5467900-d8bb-11ea-8ef2-501e5a83d9fa.png">

**Comment by maerteijn** [comment]
I encountered the same:
```
Error! An unexpected error occurred in inspect: TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/vercel/dist/index.js:2:650065
    at Array.reduce (<anonymous>)
    at A (/usr/local/lib/node_modules/vercel/dist/index.js:2:650029)
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655310)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)
```
However, the deployment was succesfully done. Retrying the same action results in the same error, so it's reproducable.

**Comment by denis-kalinichenko** [comment]
The same:

```
Error! An unexpected error occurred in inspect: TypeError: Cannot read property 'split' of undefined
91
    at S (/usr/local/lib/node_modules/vercel/dist/index.js:2:649236)
92
    at C (/usr/local/lib/node_modules/vercel/dist/index.js:2:649365)
93
    at Array.sort (<anonymous>)
94
    at A (/usr/local/lib/node_modules/vercel/dist/index.js:2:649999)
95
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655310)
96
    at runMicrotasks (<anonymous>)
97
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
98
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)
99
##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

**Comment by johnmurphy01** [comment]
Same:

```
Error! An unexpected error occurred in inspect: TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/vercel/dist/index.js:2:650065
    at Array.reduce (<anonymous>)
    at A (/usr/local/lib/node_modules/vercel/dist/index.js:2:650029)
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655310)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)

Error! An unexpected error occurred in inspect: TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/vercel/dist/index.js:2:650065
    at Array.reduce (<anonymous>)
    at A (/usr/local/lib/node_modules/vercel/dist/index.js:2:650029)
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655310)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)
##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

**Comment by joonashak** [comment]
I'm getting a similar error with a different property name:

```
Error! An unexpected error occurred in inspect: Error: val is not a non-empty string or a valid number. val=null
    at Object.e.exports [as default] (/usr/local/lib/node_modules/vercel/dist/index.js:2:1212562)
    at elapsed (/usr/local/lib/node_modules/vercel/dist/index.js:2:25757)
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655267)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)

Error! An unexpected error occurred in inspect: Error: val is not a non-empty string or a valid number. val=null
    at Object.e.exports [as default] (/usr/local/lib/node_modules/vercel/dist/index.js:2:1212562)
    at elapsed (/usr/local/lib/node_modules/vercel/dist/index.js:2:25757)
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655267)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)
##[error]The process '/usr/local/bin/npx' failed with exit code 1
```

The actual deployment on Vercel's end succeeds for me, too.

**Comment by facosta0787** [comment]
I'm getting the same error
![image](https://user-images.githubusercontent.com/17883219/89678962-ba082e80-d8b5-11ea-998b-4dd266b1b78c.png)

but the weird part is that the deployment in vercel finishes succesfully.

![image](https://user-images.githubusercontent.com/17883219/89679025-dd32de00-d8b5-11ea-9d6b-86dbb30de035.png)

**Comment by EvanLovely** [comment]
Looks to be similar to issue #28

**Comment by EvanLovely** [comment]
So the [GitHub Actions docs says](https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging) I can set the secret `ACTIONS_STEP_DEBUG` to `true` and re-run actions to get more details. I did and then saw that this is the command being ran right before the error:

```bash
vercel inspect https://my-site.vercel.app --scope team_ABC123
```

Running that locally gives me the same error:

```
Error! An unexpected error occurred in inspect: TypeError: Cannot read property 'split' of undefined
```

I tried to update to the latest cli `now@19.2.0` but had same error.

**Comment by EvanLovely** [comment]
So this is happening during the `vercel inspect` usage - which happens after the `vercel deploy` so that's why deploys are still successful. This step is most likely used to get all the useful GitHub actions outputs like deploy url (which I love BTW!). When I ran this locally, it fails right before listing the "Builds" out - I'm guessing that is an array and the cli is basically trying to run `builds.split('\n')` but `builds` is undefined. Probably an API data structure change. PS This is why optional chaining is amazing b/c then `builds?.split('\n')` wouldn't crash the whole thing.

![ScreenShot 2020-08-07 at 14 37 33@2x](https://user-images.githubusercontent.com/569699/89690768-27b75900-d8bc-11ea-99bd-0f3eecc270d1.png)

**Comment by simonhaenisch** [comment]
I've contacted Vercel Support about this, as I believe this is an upstream issue.

**Comment by sakulstra** [comment]
@simonhaenisch did you get any update? contacted them as well, but didn't get any response yet.

**Comment by simonhaenisch** [comment]
Yeah they said it's an issue with the `inspect` command but they haven't updated me since.

**Comment by EvanLovely** [comment]
Is there a GitHub issue on the https://github.com/vercel/vercel repo anyone has a link to?

**Comment by simonhaenisch** [comment]
Nope because they don't do bug tracing publicly anymore.

**Comment by EvanLovely** [comment]
Well that's a convenient way to appear less buggy 😠

**Comment by jackguoAtJogg** [comment]
That's annoying, I have to do manually deployment.

**Comment by EvanLovely** [comment]
I've got a fork that is working for me (use `EvanLovely/vercel-action@506f39d` in GitHub Actions config to use/test) and have made a PR for it: #29

**Comment by klapec** [comment]
I've filled an issue about this as well, got in response:
>Hello,
>
>There is an issue with `vercel inspect` which we are currently fixing as we speak.
>
>We will get back to you as soon as that is fixed.

**Comment by nilaeus** [comment]
It works for me now.

**Comment by klapec** [comment]
I've got a response from the Vercel support team
> The issue has been fixed for all new deployments. We are working to make it compatible with old deployments as well.

`vercel inspect` seems to be working now but this vercel action still fails with `Error! Failed to find deployment xxx in xxx`.

**Comment by simonhaenisch** [comment]
Got the same response from support as well, and new deployments with this action are working again for us.

**Comment by klapec** [comment]
@simonhaenisch 
By
> new deployments

do you mean new pull requests (assuming you're using this action for deploying PR previews?)
It seems to be still broken for me when I'm triggering new workflow runs within the same PR.

**Comment by simonhaenisch** [comment]
We use it to manually deploy master to a staging environment. It works for new commits on master now. PR previews are done by the Github Integration.
