### ISSUE TITLE
Difficulty adding multiple environment variables in vercel-args

### ISSUE THREAD

**Issue by jacobdo2** [amondnet/vercel-action#38]
I have been trying to pass multiple through the vercel args, but not having much luck.

According to the documentation here https://vercel.com/docs/cli#commands/overview/unique-options/build-env, environment variables for build time should be set as follows:

```yml
vercel-args: --build-env [NODE_ENV=pr,PR_NUMBER=${{ github.event.number }}]
```
However this fails with an error:
`Error! The specified file or directory "PR_NUMBER=423]" does not exist.`

**Comment by amondnet** [comment]
@jacobdo2 Hi, 
According to the document:
```bash
vercel --build-env KEY1=value1 --build-env KEY2=value2
```
Have you tried the following?
```bash
vercel-args: --build-env NODE_ENV=pr --build-env PR_NUMBER=${{ github.event.number }}
```

Alternatively, we can add a `build-env` argument like `alias-domains`.  It will be implemented like below. (github actions doesn't support list or map args)
- Option 1
  ```yaml
  build-env: |
    NODE_ENV=pr
    PR_NUMBER=${{ github.event.number }}
  ```
- Option 2
  ```yaml
  build-env: '[{"NODE_ENV": "pr", "PR_NUMBER": ${{ github.event.number }}]'
  ```

**Comment by jacobdo2** [comment]
I don't understand how I came across the other piece of documentation which lists the example I have indicated above, thanks for your help. Props on this repo, really helpful 👍

**Comment by dgokcin** [comment]
@amondnet @jacobdo2 is does that mean that option 1 is working?

**Comment by colinwilson** [comment]
@dgokcin Just tried... option 1 **doesn't** work.
```
Warning: Unexpected input(s) 'build-env', valid inputs are ['vercel-token', 'vercel-args', 'github-comment', 'github-token', 'github-deployment', 'working-directory', 'vercel-project-id', 'vercel-org-id', 'vercel-project-name', 'vercel-version', 'scope', 'zeit-token', 'now-args', 'now-project-id', 'now-org-id', 'alias-domains']
```
