### ISSUE TITLE
Feature request: enable users to customize github comment

### ISSUE THREAD

**Issue by sorrykim** [amondnet/vercel-action#52]
# As-is

github-comment parameter is boolean so that users can decide only whether comment will be created, not content of the comment.

# To-be (request)

github-comment parameter can be boolean or string.
if github-comment is true, use default comment content.
else if github-comment is string, create comment whose content is that string.

**Comment by sorrykim** [comment]
Can I resolve this issue on my own and make PR? @amondnet

**Comment by amondnet** [comment]
@sorrykim Yes, of course. The feature you suggested looks very useful.
