### ISSUE TITLE
Remove depracated package @now/node-server

### ISSUE THREAD

**Issue by Celtian** [amondnet/vercel-action#61]
`@now/node-server` is depracated and stopped working.

See:  https://www.npmjs.com/package/@now/node-server

Can you replace here:

https://github.com/amondnet/vercel-action/blob/master/example/express-basic-auth/now.json#L7

with 

`@vercel/node`

It would be good to menion it in readme because I spend many hours to find the cause.

Best regards!

**Comment by amondnet** [comment]
@Celtian Thank you for your good comment. My teammate went through the same thing a few days ago. I'll fix it soon.
