### ISSUE TITLE
Use branch name from ref?

### ISSUE THREAD

**Issue by Js-Brecht** [amondnet/vercel-action#78]
I was just wondering if the `ref` referenced here should be the branch name, instead of the ref path?

https://github.com/amondnet/vercel-action/blob/006f00badc059602e3d10a9862923d54552c621b/index.js#L330

It seems like it would be closer to what Vercel itself does.

For example, when doing a deployment for a push, on Vercel I get the actual branch name.

When doing it with `vercel-action`, I get this:

![image](https://user-images.githubusercontent.com/1935258/114118210-1e83ef00-9884-11eb-97e5-fea1cf05dc15.png)
![image](https://user-images.githubusercontent.com/1935258/114118223-23e13980-9884-11eb-8284-71ff50b75386.png)

----

This action has made my life much easier, btw :+1:.  Trying to get deployments working correctly on Vercel was... cumbersome.

**Comment by NullSoldier** [comment]
Yes, this is a logical bug. Without this, domains don't work by default. Also on top of that domain aliasing is broken atm in the action.

**Comment by hrgui** [comment]
I was encountering the same issue with env variables also. 

I had to change to `amondnet/vercel-action@master` to fix it for now, are we going to have a release anytime soon?
