### ISSUE TITLE
Action Failing at vercel inspect

### ISSUE THREAD

**Issue by JohnDeved** [amondnet/vercel-action#80]
first of all, thanks for creating this project. very cool!
trying it out it seems to deploy to vercel fine, but the action seems to fail before commenting on the PR/Commit.

```
/usr/local/bin/npx vercel inspect https://alpin11-ui-pg45u9g3c-alpin11.vercel.app -t ***
Vercel CLI 21.3.3

Vercel CLI 21.3.3
- Fetching deployment "https://alpin11-ui-pg45u9g3c-alpin11.vercel.app" in alpin11-developer

- Fetching deployment "https://alpin11-ui-pg45u9g3c-alpin11.vercel.app" in alpin11-developer
Error! Could not find deployment (404)

Error! Could not find deployment (404)
Error: The process '/usr/local/bin/npx' failed with exit code 1
```

**Comment by JohnDeved** [comment]
cli also fails when trying to use locally.
![image](https://user-images.githubusercontent.com/24187269/115259183-f0c76180-a131-11eb-82d6-4c1ff025ce98.png)

but clicking the URL loads the deployment as expected

**Comment by JohnDeved** [comment]
might be a issue with vercel api? anybody experiencing the same thing?

![image](https://user-images.githubusercontent.com/24187269/115260946-7dbeea80-a133-11eb-9cb2-475ba9c2489c.png)

**Comment by JohnDeved** [comment]
had to set `scope: ${{ secrets.ORG_ID }}`
was not clear. thanks

**Comment by JohnDeved** [comment]
maybe this should be made clearer in the readme? @amondnet

**Comment by Yhozen** [comment]
This wasn't added to the readme :(
